version: '3.8'

services:
  db: 
    image: postgres:16
    container_name: book-my-ticket
    restart: unless-stopped
    environment:
      POSTGRES_USER: sudo
      POSTGRES_PASSWORD: sudohu
      POSTGRES_DB: bookmyticket
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
